env:
  opts:
    sophia:
      path: /tmp/trove/data
    db:
      d: &ddbs
        compression: zstd
      u:
        *ddbs
index:
  env:
    opts:
      sophia:
        path: /tmp/trove/index
      db:
        t2o: &ddbs
          compression: zstd
        o2t:
          *ddbs
        d2v:
          *ddbs
        c:
          *ddbs
